### ISSUE TITLE
Handle disabled webclipper

### ISSUE THREAD

**Issue by mcorossigo** [rxliuli/joplin-charts#1]
Hello @rxliuli 
Saw this in the forum. It's really nice.

I had the webclipper services disabled by chances, and your app appeared white with a some error in the console. It took me a few minutes to fix.
Can you handle more gracefully the connection error, maybe by catching it's exception and showing a suggestion string to check the webclipper?

Thanks!

**Comment by rxliuli** [comment]
Well, it took me less than an hour to implement it, so I didn’t notice these problems. I will add some error hints later.
